export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_DISTRICT = "GET_DISTRICT";
export const GET_CLUSTER = "GET_CLUSTER";
export const GET_KUTIR = "GET_KUTIR";

export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBERS_FAIL = "GET_MEMBERS_FAIL";

export const GET_CHILD_ALL = "GET_CHILD_ALL";
export const GET_LACTATIC_MOTHER_ALL = "GET_LACTATIC_MOTHER_ALL";
export const GET_MOTHER_ALL = "GET_MOTHER_ALL";

export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAIL = "ADD_MEMBER_FAIL";

export const ADD_CHILD_SUCCESS = "ADD_CHILD_SUCCESS";
export const ADD_CHILD_FAIL = "ADD_CHILD_FAIL";

export const ADD_MOTHER_SUCCESS = "ADD_MOTHER_SUCCESS";
export const ADD_MOTHER_FAIL = "ADD_MOTHER_FAIL";

export const ADD_LACTIC_MOTHER_SUCCESS = "ADD_MOTHER_SUCCESS";
export const ADD_LACTIC_MOTHER_FAIL = "ADD_MOTHER_FAIL";

export const CONFIRMREGISTER_START = "CONFIRMREGISTER_START";
export const CONFIRMREGISTER_SUCCESS = "CONFIRMREGISTER_SUCCESS";
export const CONFIRMREGISTER_FAILURE = "CONFIRMREGISTER_FAILURE";